# Generated by Django 4.2.7 on 2025-05-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('archived', 'Archivada')], default='pending', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='prioridad')),
                ('completed', models.BooleanField(default=False, verbose_name='completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('reminder', models.DateTimeField(blank=True, null=True, verbose_name='recordatorio')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
